import { LINE_STYLES } from "../constants/packaging";
import { boundsForDieline } from "../geometry/primitives/bounds";
import type { Dieline, Line, Polygon } from "../types/geometry";

const lineSvg = (line: Line): string => {
  const style = LINE_STYLES[line.type as keyof typeof LINE_STYLES] ?? LINE_STYLES.cut;
  const dash =
    line.type === "fold"
      ? ' stroke-dasharray="5 4"'
      : line.type === "safe" || line.type === "perforation"
        ? ' stroke-dasharray="1.5 3"'
        : "";

  return `<line x1="${line.start.x}" y1="${line.start.y}" x2="${line.end.x}" y2="${line.end.y}" stroke="${style.stroke}" stroke-width="0.35" fill="none"${dash} data-line-type="${line.type}" />`;
};

const polygonSvg = (polygon: Polygon): string => {
  const points = polygon.points.map((point) => `${point.x},${point.y}`).join(" ");
  return `<polygon points="${points}" fill="rgba(255, 198, 87, 0.16)" stroke="none" data-area="${polygon.label ?? polygon.id}" />`;
};

export const exportDielineToSvg = (dieline: Dieline): string => {
  const bounds = boundsForDieline(dieline, 12);
  const lines = [
    ...dieline.bleeds,
    ...dieline.safeZones,
    ...dieline.folds,
    ...dieline.cuts,
    ...dieline.perforations,
  ];

  return `<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="${bounds.width}mm" height="${bounds.height}mm" viewBox="${bounds.minX} ${bounds.minY} ${bounds.width} ${bounds.height}">
  <title>${dieline.name}</title>
  <desc>Generated by OPENDIELINE. Units are millimeters.</desc>
  <defs>
    <style>
      text { font-family: Arial, sans-serif; font-size: 4px; fill: #172026; }
    </style>
  </defs>
  <g id="glue-areas">${dieline.glueAreas.map(polygonSvg).join("\n    ")}</g>
  <g id="bleed-lines">${dieline.bleeds.map(lineSvg).join("\n    ")}</g>
  <g id="safe-zones">${dieline.safeZones.map(lineSvg).join("\n    ")}</g>
  <g id="fold-lines">${dieline.folds.map(lineSvg).join("\n    ")}</g>
  <g id="cut-lines">${dieline.cuts.map(lineSvg).join("\n    ")}</g>
  <g id="perforation-lines">${dieline.perforations.map(lineSvg).join("\n    ")}</g>
  <g id="dimension-labels">
    ${dieline.dimensions
      .map(
        (dimension) =>
          `<text x="${(dimension.start.x + dimension.end.x) / 2}" y="${(dimension.start.y + dimension.end.y) / 2}" text-anchor="middle">${dimension.text}</text>`,
      )
      .join("\n    ")}
  </g>
</svg>`;
};

export const svgBlob = (dieline: Dieline): Blob =>
  new Blob([exportDielineToSvg(dieline)], { type: "image/svg+xml;charset=utf-8" });
